version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://cur8fun:password@db:5432/cur8fun_db
      - SECRET_KEY=your-secret-key-here
      - WORKERS=2
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=cur8fun_db
      - POSTGRES_USER=cur8fun
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
